version: '1.0'
stages:
  - prepare
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'murlikjha/gs-gradle'
    revision: master
    git: github
  BuildingDockerImage:
    title: Building Docker Image
    stage: build
    type: build
    image_name: docker-sample-app
    working_directory: ./
    tag: 'multi-stage'
    dockerfile: Dockerfile
